### ISSUE TITLE
IVY - Up Arrow in Minibuffer

### ISSUE THREAD

**Issue by am2605** [purcell/emacs.d#473]
I'm using Emacs 25.2 on Windows 10.

Over the last couple of weeks I've suddenly started seeing some strangeness in my minibuffer when I navigate up and down the list of matches with the arrow keys.

What happens is when I press the up arrow I see:

The message:

`"beginning of history; no preceeding item" `

and the list of matches disappears.

I have fixed this by adding the following to my init-local.el:

`(define-key ivy-minibuffer-map (kbd "<up>") #'ivy-previous-line)`

I noticed the init-ivy.el maps this to `ivy-previous-line-or-history` so I'm not certain if some behaviour has changed in that function, or whether it's something environmental in my setup.

Has anyone else noticed issues with this?

**Comment by purcell** [comment]
Hmm, I don't see exactly that behaviour, but I do see *some* weirdness with it: if I start `ivy-switch-buffer` hit `<down>` a few times, then trigger `ivy-previous-line-or-history`, the completion list immediately changes to one that contains only the current buffer and all the "virtual" buffers.

So I feel like this is a weird `ivy` regression. Any thoughts, @abo-abo?

**Comment by purcell** [comment]
Aha: it seems that `ivy-previous-line-or-history` *immediately* inserts the last history item at the completion prompt, even in the case where the currently-selected line is not the first in the list. So that seems like a bug.

**Comment by purcell** [comment]
Patch for that submitted in https://github.com/abo-abo/swiper/pull/1137.

**Comment by am2605** [comment]
Thanks for your quick response on this!

________________________________

**Comment by purcell** [comment]
Fixed upstream now.

**Comment by sashaaaaaaaaa** [comment]
I'm still having the same bug, when i press the up arrow it inserts the last thing i wrote, doesn't go back in the completion list. Doesn't matter where i am in the list.

**Comment by purcell** [comment]
@sashaaaaaaaaa Okay, but the last time it was an upstream bug, so this must be a regression, not an issue for this repo.

**Comment by purcell** [comment]
I patched this locally in the end.

**Comment by purcell** [comment]
Upstream fix submitted in https://github.com/abo-abo/swiper/pull/2447.
